# Generated by Django 3.2 on 2023-02-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_markdown',
            field=models.TextField(default='', verbose_name='マークダウン形式の本文'),
            preserve_default=False,
        ),
    ]
